# Generated by Django 5.1.3 on 2024-12-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
