# Generated by Django 5.1.3 on 2024-12-02 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
