# Generated by Django 5.1.3 on 2024-12-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='is_found',
            new_name='is_approachable',
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
