# Generated by Django 5.1.3 on 2024-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_animal_is_approachable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_approachable',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
